# pylint: skip-file
# Generated by Django 3.2.24 on 2024-02-24 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenerativeAIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(choices=[('openai_chat', 'OpenAI Chat'), ('openai_images', 'OpenAI Images')], max_length=128)),
                ('model_name', models.CharField(max_length=1024)),
                ('model_parameters', models.TextField(default='{}', max_length=1048576)),
            ],
        ),
    ]
