# pylint: skip-file
# Generated by Django 3.2.24 on 2024-02-24 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_generative_ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generativeaimodel',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='generativeaimodel',
            name='model_id',
            field=models.SlugField(default='new-model', max_length=128, unique=True),
        ),
    ]
