# pylint: skip-file
# Generated by Django 3.2.24 on 2024-02-24 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simple_generative_ai', '0002_auto_20240224_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerativeAIModelRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested', models.DateTimeField()),
                ('request', models.TextField(max_length=1048576)),
                ('response', models.TextField(blank=True, max_length=1048576, null=True)),
                ('successful', models.BooleanField(default=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='simple_generative_ai.generativeaimodel')),
            ],
        ),
    ]
