# pylint: skip-file
# Generated by Django 5.2.4 on 2025-08-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_generative_ai', '0005_alter_generativeaimodel_model_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generativeaimodel',
            name='model_type',
            field=models.CharField(choices=[('anthropic_claude', 'Anthropic Claude'), ('openai_chat', 'OpenAI Chat (Inc. Azure)'), ('openai_chat_legacy', 'OpenAI Chat (Legacy HTTP Only)'), ('openai_images', 'OpenAI Images')], max_length=128),
        ),
    ]
